In [43]:
import pandas as pd

In [44]:
df = pd.read_csv(r"C:\Users\clmen\OneDrive\Documents\ESCP\PYTHON\nba_games.csv",index_col=0)
df

C:\Users\clmen\AppData\Local\Temp\ipykernel_4476\2856975357.py:1: DtypeWarning: Columns (28) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"C:\Users\clmen\OneDrive\Documents\ESCP\PYTHON\nba_games.csv",index_col=0)

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,240.0,240.0,39.0,81.0,0.481,6.0,20.0,0.300,14.0,18.0,...,22.8,29.0,178.0,111.0,DAL,95,1,2016,2015-12-09,True
1,240.0,240.0,36.0,100.0,0.360,7.0,31.0,0.226,16.0,19.0,...,50.0,32.6,152.0,111.0,ATL,98,0,2016,2015-12-09,False
2,240.0,240.0,37.0,85.0,0.435,8.0,19.0,0.421,17.0,23.0,...,20.0,30.9,148.0,116.0,SAS,107,1,2018,2017-10-18,False
3,240.0,240.0,41.0,89.0,0.461,8.0,21.0,0.381,17.0,19.0,...,28.6,30.9,138.0,118.0,MIN,99,0,2018,2017-10-18,True
4,240.0,240.0,27.0,86.0,0.314,6.0,26.0,0.231,15.0,20.0,...,16.8,30.9,157.0,90.0,MEM,92,1,2021,2021-04-30,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,240.0,240.0,35.0,81.0,0.432,11.0,26.0,0.423,27.0,36.0,...,34.2,33.7,160.0,118.0,OKC,92,0,2019,2018-10-19,True
17768,240.0,240.0,37.0,74.0,0.500,13.0,25.0,0.520,26.0,37.0,...,25.0,30.0,139.0,129.0,ORL,108,1,2017,2016-12-14,True
17769,240.0,240.0,42.0,89.0,0.472,14.0,33.0,0.424,10.0,20.0,...,25.6,29.9,175.0,126.0,LAC,113,0,2017,2016-12-14,False
17770,240.0,240.0,41.0,85.0,0.482,9.0,26.0,0.346,26.0,30.0,...,27.7,27.1,150.0,126.0,MIA,106,1,2020,2020-09-19,True
17771,240.0,240.0,33.0,85.0,0.388,12.0,44.0,0.273,28.0,34.0,...,51.5,36.2,141.0,114.0,BOS,117,0,2020,2020-09-19,False

In [45]:
#Let's order our df
df = df.sort_values("date")
df = df.reset_index(drop=True)
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,240.0,240.0,35.0,83.0,0.422,6.0,18.0,0.333,19.0,27.0,...,69.4,43.7,206.0,104.0,GSW,111,1,2016,2015-10-27,False
1,240.0,240.0,38.0,94.0,0.404,9.0,29.0,0.310,10.0,17.0,...,53.2,34.6,162.0,104.0,CHI,97,1,2016,2015-10-27,False
2,240.0,240.0,37.0,87.0,0.425,7.0,19.0,0.368,16.0,23.0,...,30.4,29.0,138.0,105.0,CLE,95,0,2016,2015-10-27,True
3,240.0,240.0,41.0,96.0,0.427,9.0,30.0,0.300,20.0,22.0,...,37.5,38.9,201.0,120.0,NOP,95,0,2016,2015-10-27,True
4,240.0,240.0,37.0,82.0,0.451,8.0,27.0,0.296,12.0,15.0,...,33.3,23.6,132.0,104.0,DET,106,0,2016,2015-10-27,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,240.0,240.0,34.0,85.0,0.400,15.0,38.0,0.395,14.0,19.0,...,42.9,36.3,133.0,112.0,GSW,107,0,2022,2022-06-10,False
17768,240.0,240.0,41.0,88.0,0.466,9.0,40.0,0.225,13.0,15.0,...,45.0,94.4,300.0,112.0,BOS,94,0,2022,2022-06-13,True
17769,240.0,240.0,31.0,75.0,0.413,11.0,32.0,0.344,21.0,31.0,...,33.3,36.2,222.0,107.0,GSW,104,1,2022,2022-06-13,False
17770,240.0,240.0,34.0,80.0,0.425,11.0,28.0,0.393,11.0,12.0,...,33.3,31.5,186.0,111.0,GSW,103,0,2022,2022-06-16,False
17771,240.0,240.0,38.0,92.0,0.413,19.0,46.0,0.413,8.0,8.0,...,100.0,42.6,141.0,126.0,BOS,90,1,2022,2022-06-16,True

In [46]:
#data clean, by deleting the residual column

del df["mp.1"]
del df["mp_opp.1"]
del df["index_opp"] 
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,240.0,35.0,83.0,0.422,6.0,18.0,0.333,19.0,27.0,0.704,...,69.4,43.7,206.0,104.0,GSW,111,1,2016,2015-10-27,False
1,240.0,38.0,94.0,0.404,9.0,29.0,0.310,10.0,17.0,0.588,...,53.2,34.6,162.0,104.0,CHI,97,1,2016,2015-10-27,False
2,240.0,37.0,87.0,0.425,7.0,19.0,0.368,16.0,23.0,0.696,...,30.4,29.0,138.0,105.0,CLE,95,0,2016,2015-10-27,True
3,240.0,41.0,96.0,0.427,9.0,30.0,0.300,20.0,22.0,0.909,...,37.5,38.9,201.0,120.0,NOP,95,0,2016,2015-10-27,True
4,240.0,37.0,82.0,0.451,8.0,27.0,0.296,12.0,15.0,0.800,...,33.3,23.6,132.0,104.0,DET,106,0,2016,2015-10-27,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,240.0,34.0,85.0,0.400,15.0,38.0,0.395,14.0,19.0,0.737,...,42.9,36.3,133.0,112.0,GSW,107,0,2022,2022-06-10,False
17768,240.0,41.0,88.0,0.466,9.0,40.0,0.225,13.0,15.0,0.867,...,45.0,94.4,300.0,112.0,BOS,94,0,2022,2022-06-13,True
17769,240.0,31.0,75.0,0.413,11.0,32.0,0.344,21.0,31.0,0.677,...,33.3,36.2,222.0,107.0,GSW,104,1,2022,2022-06-13,False
17770,240.0,34.0,80.0,0.425,11.0,28.0,0.393,11.0,12.0,0.917,...,33.3,31.5,186.0,111.0,GSW,103,0,2022,2022-06-16,False
17771,240.0,38.0,92.0,0.413,19.0,46.0,0.413,8.0,8.0,1.000,...,100.0,42.6,141.0,126.0,BOS,90,1,2022,2022-06-16,True

In [47]:
#setup a target to predict what a team did in the next game

def add_target(team):
    team["target"] = team["won"].shift(-1)
    return team

df = df.groupby("team", group_keys=False).apply(add_target)

C:\Users\clmen\AppData\Local\Temp\ipykernel_4476\3939461052.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\clmen\AppData\Local\Temp\ipykernel_4476\3939461052.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\clmen\AppData\Local\Temp\ipykernel_4476\3939461052.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\clmen\AppData\Local\Temp\ipykernel_4476\3939461052.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\clmen\AppData\Local\Temp\ipykernel_4476\3939461052.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\clmen\AppData\Local\Temp\ipykernel_4476\3939461052.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\clmen\AppData\Local\Temp\ipykernel_4476\3939461052.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\clmen\AppData\Local\Temp\ipykernel_4476\3939461052.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\clmen\AppData\Local\Temp\ipykernel_4476\3939461052.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\clmen\AppData\Local\Temp\ipykernel_4476\3939461052.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\clmen\AppData\Local\Temp\ipykernel_4476\3939461052.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\clmen\AppData\Local\Temp\ipykernel_4476\3939461052.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\clmen\AppData\Local\Temp\ipykernel_4476\3939461052.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\clmen\AppData\Local\Temp\ipykernel_4476\3939461052.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\clmen\AppData\Local\Temp\ipykernel_4476\3939461052.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\clmen\AppData\Local\Temp\ipykernel_4476\3939461052.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\clmen\AppData\Local\Temp\ipykernel_4476\3939461052.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\clmen\AppData\Local\Temp\ipykernel_4476\3939461052.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\clmen\AppData\Local\Temp\ipykernel_4476\3939461052.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\clmen\AppData\Local\Temp\ipykernel_4476\3939461052.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\clmen\AppData\Local\Temp\ipykernel_4476\3939461052.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\clmen\AppData\Local\Temp\ipykernel_4476\3939461052.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\clmen\AppData\Local\Temp\ipykernel_4476\3939461052.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\clmen\AppData\Local\Temp\ipykernel_4476\3939461052.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\clmen\AppData\Local\Temp\ipykernel_4476\3939461052.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\clmen\AppData\Local\Temp\ipykernel_4476\3939461052.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\clmen\AppData\Local\Temp\ipykernel_4476\3939461052.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\clmen\AppData\Local\Temp\ipykernel_4476\3939461052.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\clmen\AppData\Local\Temp\ipykernel_4476\3939461052.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)
C:\Users\clmen\AppData\Local\Temp\ipykernel_4476\3939461052.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  team["target"] = team["won"].shift(-1)

In [48]:
#Let's take our favorite team
df[df["team"] == "GSW"]

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
3,240.0,41.0,96.0,0.427,9.0,30.0,0.300,20.0,22.0,0.909,...,38.9,201.0,120.0,NOP,95,0,2016,2015-10-27,True,True
44,240.0,43.0,93.0,0.462,9.0,26.0,0.346,17.0,25.0,0.680,...,37.5,151.0,118.0,HOU,92,1,2016,2015-10-30,True,True
67,240.0,46.0,84.0,0.548,17.0,30.0,0.567,25.0,35.0,0.714,...,36.1,218.0,131.0,NOP,120,1,2016,2015-10-31,True,True
98,240.0,43.0,84.0,0.512,11.0,25.0,0.440,22.0,30.0,0.733,...,44.3,106.0,126.0,MEM,69,0,2016,2015-11-02,True,True
137,240.0,39.0,85.0,0.459,10.0,26.0,0.385,24.0,31.0,0.774,...,32.9,250.0,122.0,LAC,108,0,2016,2015-11-04,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17762,240.0,39.0,86.0,0.453,15.0,37.0,0.405,14.0,20.0,0.700,...,35.2,300.0,117.0,BOS,88,0,2022,2022-06-05,True,False
17764,240.0,36.0,78.0,0.462,15.0,40.0,0.375,13.0,15.0,0.867,...,28.8,175.0,117.0,BOS,116,1,2022,2022-06-08,False,True
17766,240.0,40.0,91.0,0.440,15.0,43.0,0.349,12.0,15.0,0.800,...,32.4,205.0,120.0,BOS,97,1,2022,2022-06-10,True,True
17768,240.0,41.0,88.0,0.466,9.0,40.0,0.225,13.0,15.0,0.867,...,94.4,300.0,112.0,BOS,94,0,2022,2022-06-13,True,True
17771,240.0,38.0,92.0,0.413,19.0,46.0,0.413,8.0,8.0,1.000,...,42.6,141.0,126.0,BOS,90,1,2022,2022-06-16,True,NaN

In [49]:
#NaN in target is the last game of the season 
df["target"][pd.isnull(df["target"])] = 2

C:\Users\clmen\AppData\Local\Temp\ipykernel_4476\2691924771.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["target"][pd.isnull(df["target"])] = 2

In [50]:
#Convert in Boolean so we can get 0 = loss / 1 = win / 2= no data for the next game (no more game in the season)
df["target"] = df["target"].astype(int, errors="ignore")
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,240.0,35.0,83.0,0.422,6.0,18.0,0.333,19.0,27.0,0.704,...,43.7,206.0,104.0,GSW,111,1,2016,2015-10-27,False,0
1,240.0,38.0,94.0,0.404,9.0,29.0,0.310,10.0,17.0,0.588,...,34.6,162.0,104.0,CHI,97,1,2016,2015-10-27,False,1
2,240.0,37.0,87.0,0.425,7.0,19.0,0.368,16.0,23.0,0.696,...,29.0,138.0,105.0,CLE,95,0,2016,2015-10-27,True,1
3,240.0,41.0,96.0,0.427,9.0,30.0,0.300,20.0,22.0,0.909,...,38.9,201.0,120.0,NOP,95,0,2016,2015-10-27,True,1
4,240.0,37.0,82.0,0.451,8.0,27.0,0.296,12.0,15.0,0.800,...,23.6,132.0,104.0,DET,106,0,2016,2015-10-27,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,240.0,34.0,85.0,0.400,15.0,38.0,0.395,14.0,19.0,0.737,...,36.3,133.0,112.0,GSW,107,0,2022,2022-06-10,False,0
17768,240.0,41.0,88.0,0.466,9.0,40.0,0.225,13.0,15.0,0.867,...,94.4,300.0,112.0,BOS,94,0,2022,2022-06-13,True,1
17769,240.0,31.0,75.0,0.413,11.0,32.0,0.344,21.0,31.0,0.677,...,36.2,222.0,107.0,GSW,104,1,2022,2022-06-13,False,0
17770,240.0,34.0,80.0,0.425,11.0,28.0,0.393,11.0,12.0,0.917,...,31.5,186.0,111.0,GSW,103,0,2022,2022-06-16,False,2
17771,240.0,38.0,92.0,0.413,19.0,46.0,0.413,8.0,8.0,1.000,...,42.6,141.0,126.0,BOS,90,1,2022,2022-06-16,True,2

In [51]:
#Check if this is perfectly balance
print(df["won"].value_counts())
print(df["target"].value_counts())

won
False    8886
True     8886
Name: count, dtype: int64
target
1    8872
0    8870
2      30
Name: count, dtype: int64

In [52]:
nulls = pd.isnull(df)
nulls = nulls.sum()

In [53]:
nulls = nulls[nulls > 0]

In [54]:
valid_columns = df.columns[~df.columns.isin(nulls.index)]

In [55]:
#We remove the extra column that we don't need
valid_columns

Index(['mp', 'fg', 'fga', 'fg%', '3p', '3pa', '3p%', 'ft', 'fta', 'ft%',
       ...
       'usg%_max_opp', 'ortg_max_opp', 'drtg_max_opp', 'team_opp', 'total_opp',
       'home_opp', 'season', 'date', 'won', 'target'],
      dtype='object', length=142)

In [56]:
#Check data clean
df = df[valid_columns].copy()
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,240.0,35.0,83.0,0.422,6.0,18.0,0.333,19.0,27.0,0.704,...,43.7,206.0,104.0,GSW,111,1,2016,2015-10-27,False,0
1,240.0,38.0,94.0,0.404,9.0,29.0,0.310,10.0,17.0,0.588,...,34.6,162.0,104.0,CHI,97,1,2016,2015-10-27,False,1
2,240.0,37.0,87.0,0.425,7.0,19.0,0.368,16.0,23.0,0.696,...,29.0,138.0,105.0,CLE,95,0,2016,2015-10-27,True,1
3,240.0,41.0,96.0,0.427,9.0,30.0,0.300,20.0,22.0,0.909,...,38.9,201.0,120.0,NOP,95,0,2016,2015-10-27,True,1
4,240.0,37.0,82.0,0.451,8.0,27.0,0.296,12.0,15.0,0.800,...,23.6,132.0,104.0,DET,106,0,2016,2015-10-27,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,240.0,34.0,85.0,0.400,15.0,38.0,0.395,14.0,19.0,0.737,...,36.3,133.0,112.0,GSW,107,0,2022,2022-06-10,False,0
17768,240.0,41.0,88.0,0.466,9.0,40.0,0.225,13.0,15.0,0.867,...,94.4,300.0,112.0,BOS,94,0,2022,2022-06-13,True,1
17769,240.0,31.0,75.0,0.413,11.0,32.0,0.344,21.0,31.0,0.677,...,36.2,222.0,107.0,GSW,104,1,2022,2022-06-13,False,0
17770,240.0,34.0,80.0,0.425,11.0,28.0,0.393,11.0,12.0,0.917,...,31.5,186.0,111.0,GSW,103,0,2022,2022-06-16,False,2
17771,240.0,38.0,92.0,0.413,19.0,46.0,0.413,8.0,8.0,1.000,...,42.6,141.0,126.0,BOS,90,1,2022,2022-06-16,True,2

<center>

# MACHINE LEARNING PART

</center>

In [57]:
#feature selecture 

from sklearn.model_selection import TimeSeriesSplit
from sklearn.feature_selection import SequentialFeatureSelector 
from sklearn.linear_model import RidgeClassifier

rr = RidgeClassifier(alpha=1)
split = TimeSeriesSplit(n_splits=3)
sfs = SequentialFeatureSelector(rr, n_features_to_select=30, direction="forward", cv = split)

In [58]:
removed_columns = ["season", "date", "won", "target", "team", "team_opp"]

In [59]:
#We select the column except the removed one
selected_columns = df.columns[~df.columns.isin(removed_columns)]

In [60]:
from sklearn.preprocessing import MinMaxScaler

# Identify and print the problematic values across all columns
problematic_values = df.loc[~df[selected_columns].applymap(lambda x: str(x).replace('.', '', 1).isdigit()).all(axis=1)]
print("Problematic Values:", problematic_values)

# Remove rows with non-numeric values
df = df[df[selected_columns].applymap(lambda x: str(x).replace('.', '', 1).isdigit()).all(axis=1)]

scaler = MinMaxScaler()
df[selected_columns] = scaler.fit_transform(df[selected_columns])
df

C:\Users\clmen\AppData\Local\Temp\ipykernel_4476\2428503241.py:4: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  problematic_values = df.loc[~df[selected_columns].applymap(lambda x: str(x).replace('.', '', 1).isdigit()).all(axis=1)]

Problematic Values:           mp    fg    fga    fg%    3p   3pa    3p%    ft   fta    ft%  ...  \
14     240.0  42.0   93.0  0.452   9.0  23.0  0.391  29.0  35.0  0.829  ...
15     240.0  30.0   86.0  0.349   9.0  18.0  0.500  28.0  31.0  0.903  ...
68     240.0  39.0   88.0  0.443   6.0  15.0  0.400  13.0  18.0  0.722  ...
74     240.0  28.0   70.0  0.400   4.0  17.0  0.235  16.0  21.0  0.762  ...
128    240.0  45.0   83.0  0.542  14.0  23.0  0.609  14.0  22.0  0.636  ...
...      ...   ...    ...    ...   ...   ...    ...   ...   ...    ...  ...
17726  240.0  31.0   78.0  0.397   6.0  18.0  0.333  18.0  21.0  0.857  ...
17729  240.0  41.0  104.0  0.394  20.0  53.0  0.377   8.0  11.0  0.727  ...
17731  240.0  34.0   96.0  0.354  15.0  36.0  0.417  13.0  20.0  0.650  ...
17733  240.0  33.0   90.0  0.367   4.0  33.0  0.121  11.0  16.0  0.688  ...
17734  240.0  37.0   88.0  0.420  22.0  55.0  0.400  13.0  18.0  0.722  ...

       usg%_max_opp  ortg_max_opp  drtg_max_opp  team_opp  total_opp  \
14             32.5         140.0         137.0       MIL         97
15             43.3         205.0         114.0       NYK        122
68             48.1         160.0         114.0       IND         76
74             44.8         191.0          92.0       UTA         97
128            33.9         228.0         128.0       SAC         97
...             ...           ...           ...       ...        ...
17726          53.2         250.0         108.0       DAL        113
17729          33.1         142.0         121.0       MEM         96
17731          30.1         144.0         109.0       GSW        110
17733          28.3         300.0          93.0       BOS        109
17734          42.6         209.0         120.0       MIL         81

       home_opp  season        date    won  target
14            1    2016  2015-10-28   True       0
15            0    2016  2015-10-28  False       0
68            1    2016  2015-10-31   True       0
74            0    2016  2015-10-31  False       1
128           0    2016  2015-11-04   True       0
...         ...     ...         ...    ...     ...
17726         1    2022  2022-05-12  False       0
17729         0    2022  2022-05-13   True       1
17731         1    2022  2022-05-13  False       2
17733         1    2022  2022-05-15  False       2
17734         0    2022  2022-05-15   True       0

[1273 rows x 142 columns]

C:\Users\clmen\AppData\Local\Temp\ipykernel_4476\2428503241.py:8: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df[df[selected_columns].applymap(lambda x: str(x).replace('.', '', 1).isdigit()).all(axis=1)]
C:\Users\clmen\AppData\Local\Temp\ipykernel_4476\2428503241.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[selected_columns] = scaler.fit_transform(df[selected_columns])

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,0.0,0.363636,0.338235,0.368675,0.206897,0.212121,0.395487,0.418605,0.412698,0.654609,...,0.277279,0.554502,0.309524,GSW,0.451923,1.0,2016,2015-10-27,False,0
1,0.0,0.431818,0.500000,0.325301,0.310345,0.378788,0.368171,0.209302,0.253968,0.519253,...,0.160462,0.345972,0.309524,CHI,0.317308,1.0,2016,2015-10-27,False,1
2,0.0,0.409091,0.397059,0.375904,0.241379,0.227273,0.437055,0.348837,0.349206,0.645274,...,0.088575,0.232227,0.321429,CLE,0.298077,0.0,2016,2015-10-27,True,1
3,0.0,0.500000,0.529412,0.380723,0.310345,0.393939,0.356295,0.441860,0.333333,0.893816,...,0.215661,0.530806,0.500000,NOP,0.298077,0.0,2016,2015-10-27,True,1
4,0.0,0.409091,0.323529,0.438554,0.275862,0.348485,0.351544,0.255814,0.222222,0.766628,...,0.019255,0.203791,0.309524,DET,0.403846,0.0,2016,2015-10-27,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,0.0,0.340909,0.367647,0.315663,0.517241,0.515152,0.469121,0.302326,0.285714,0.693116,...,0.182285,0.208531,0.404762,GSW,0.413462,0.0,2022,2022-06-10,False,0
17768,0.0,0.500000,0.411765,0.474699,0.310345,0.545455,0.267221,0.279070,0.222222,0.844807,...,0.928113,1.000000,0.404762,BOS,0.288462,0.0,2022,2022-06-13,True,1
17769,0.0,0.272727,0.220588,0.346988,0.379310,0.424242,0.408551,0.465116,0.476190,0.623104,...,0.181001,0.630332,0.345238,GSW,0.384615,1.0,2022,2022-06-13,False,0
17770,0.0,0.340909,0.294118,0.375904,0.379310,0.363636,0.466746,0.232558,0.174603,0.903151,...,0.120668,0.459716,0.392857,GSW,0.375000,0.0,2022,2022-06-16,False,2
17771,0.0,0.431818,0.470588,0.346988,0.655172,0.636364,0.490499,0.162791,0.111111,1.000000,...,0.263158,0.246445,0.571429,BOS,0.250000,1.0,2022,2022-06-16,True,2

In [61]:
# Fit the SequentialFeatureSelector (sfs) using selected columns and the target variable in the DataFrame


sfs.fit(df[selected_columns], df["target"])

SequentialFeatureSelector(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
                          estimator=RidgeClassifier(alpha=1),
                          n_features_to_select=30)

In [62]:
predictors = list(selected_columns[sfs.get_support()])
predictors

['pf',
 'orb%',
 'trb%',
 'usg%',
 'fta_max',
 'pf_max',
 '+/-_max',
 'drb%_max',
 'trb%_max',
 'tov%_max',
 'drtg_max',
 '3p_opp',
 '3pa_opp',
 'orb_opp',
 'blk_opp',
 'ftr_opp',
 'drb%_opp',
 'trb%_opp',
 'usg%_opp',
 'fga_max_opp',
 '3pa_max_opp',
 'ft%_max_opp',
 'ast_max_opp',
 'stl_max_opp',
 'blk_max_opp',
 'orb%_max_opp',
 'drb%_max_opp',
 'stl%_max_opp',
 'blk%_max_opp',
 'usg%_max_opp']

In [63]:
#split our data by season
def backtest(data, model, predictors, start= 2, step=1):
    all_predictions = []

    seasons = sorted(data["season"].unique())

    for i in range(start, len(seasons), step):
        season = seasons[i]
        train = data[data["season"] < season]
        test = data[data["season"] == season]

        model.fit(train[predictors], train["target"])

        preds = model.predict(test[predictors])
        preds = pd.Series(preds, index=test.index)

        combined = pd.concat([test["target"],preds], axis=1)
        combined.columns = ["actual", "prediction"]

        all_predictions.append(combined)
    return pd.concat(all_predictions)

In [64]:
#We can check our prediction correct (actual = prediction) and the incorrect

predictions = backtest(df, rr, predictors)
predictions

       actual  prediction
5250        1           1
5251        1           0
5252        0           0
5253        1           0
5254        0           1
...       ...         ...
17767       0           0
17768       1           0
17769       0           1
17770       2           0
17771       2           0

[11609 rows x 2 columns]

In [65]:
#Get the accuracy_score of our predictions

from sklearn.metrics import accuracy_score

predictions = predictions[predictions["actual"] != 2]
accuracy_score(predictions["actual"], predictions["prediction"])

0.5385478718812052

In [66]:
#Improve our model with reality => we know that teams playing at home have a clear advantage

df.groupby("home").apply(lambda x: x[x["won"] == 1].shape[0] / x.shape[0])

home
0.0    0.429818
1.0    0.570130
dtype: float64

In [67]:
#Let's add extra columns

df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,0.0,0.363636,0.338235,0.368675,0.206897,0.212121,0.395487,0.418605,0.412698,0.654609,...,0.277279,0.554502,0.309524,GSW,0.451923,1.0,2016,2015-10-27,False,0
1,0.0,0.431818,0.500000,0.325301,0.310345,0.378788,0.368171,0.209302,0.253968,0.519253,...,0.160462,0.345972,0.309524,CHI,0.317308,1.0,2016,2015-10-27,False,1
2,0.0,0.409091,0.397059,0.375904,0.241379,0.227273,0.437055,0.348837,0.349206,0.645274,...,0.088575,0.232227,0.321429,CLE,0.298077,0.0,2016,2015-10-27,True,1
3,0.0,0.500000,0.529412,0.380723,0.310345,0.393939,0.356295,0.441860,0.333333,0.893816,...,0.215661,0.530806,0.500000,NOP,0.298077,0.0,2016,2015-10-27,True,1
4,0.0,0.409091,0.323529,0.438554,0.275862,0.348485,0.351544,0.255814,0.222222,0.766628,...,0.019255,0.203791,0.309524,DET,0.403846,0.0,2016,2015-10-27,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,0.0,0.340909,0.367647,0.315663,0.517241,0.515152,0.469121,0.302326,0.285714,0.693116,...,0.182285,0.208531,0.404762,GSW,0.413462,0.0,2022,2022-06-10,False,0
17768,0.0,0.500000,0.411765,0.474699,0.310345,0.545455,0.267221,0.279070,0.222222,0.844807,...,0.928113,1.000000,0.404762,BOS,0.288462,0.0,2022,2022-06-13,True,1
17769,0.0,0.272727,0.220588,0.346988,0.379310,0.424242,0.408551,0.465116,0.476190,0.623104,...,0.181001,0.630332,0.345238,GSW,0.384615,1.0,2022,2022-06-13,False,0
17770,0.0,0.340909,0.294118,0.375904,0.379310,0.363636,0.466746,0.232558,0.174603,0.903151,...,0.120668,0.459716,0.392857,GSW,0.375000,0.0,2022,2022-06-16,False,2
17771,0.0,0.431818,0.470588,0.346988,0.655172,0.636364,0.490499,0.162791,0.111111,1.000000,...,0.263158,0.246445,0.571429,BOS,0.250000,1.0,2022,2022-06-16,True,2

In [68]:
df_rolling = df[list(selected_columns) + ["won" , "team", "season"]]
df_rolling

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,blk%_max_opp,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,total_opp,home_opp,won,team,season
0,0.0,0.363636,0.338235,0.368675,0.206897,0.212121,0.395487,0.418605,0.412698,0.654609,...,0.079,0.679245,0.277279,0.554502,0.309524,0.451923,1.0,False,NOP,2016
1,0.0,0.431818,0.500000,0.325301,0.310345,0.378788,0.368171,0.209302,0.253968,0.519253,...,0.140,0.509434,0.160462,0.345972,0.309524,0.317308,1.0,False,CLE,2016
2,0.0,0.409091,0.397059,0.375904,0.241379,0.227273,0.437055,0.348837,0.349206,0.645274,...,0.185,0.270440,0.088575,0.232227,0.321429,0.298077,0.0,True,CHI,2016
3,0.0,0.500000,0.529412,0.380723,0.310345,0.393939,0.356295,0.441860,0.333333,0.893816,...,0.063,0.344864,0.215661,0.530806,0.500000,0.298077,0.0,True,GSW,2016
4,0.0,0.409091,0.323529,0.438554,0.275862,0.348485,0.351544,0.255814,0.222222,0.766628,...,0.047,0.300839,0.019255,0.203791,0.309524,0.403846,0.0,False,ATL,2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17767,0.0,0.340909,0.367647,0.315663,0.517241,0.515152,0.469121,0.302326,0.285714,0.693116,...,0.103,0.401468,0.182285,0.208531,0.404762,0.413462,0.0,False,BOS,2022
17768,0.0,0.500000,0.411765,0.474699,0.310345,0.545455,0.267221,0.279070,0.222222,0.844807,...,0.124,0.423480,0.928113,1.000000,0.404762,0.288462,0.0,True,GSW,2022
17769,0.0,0.272727,0.220588,0.346988,0.379310,0.424242,0.408551,0.465116,0.476190,0.623104,...,0.076,0.300839,0.181001,0.630332,0.345238,0.384615,1.0,False,BOS,2022
17770,0.0,0.340909,0.294118,0.375904,0.379310,0.363636,0.466746,0.232558,0.174603,0.903151,...,0.063,0.300839,0.120668,0.459716,0.392857,0.375000,0.0,False,BOS,2022
17771,0.0,0.431818,0.470588,0.346988,0.655172,0.636364,0.490499,0.162791,0.111111,1.000000,...,0.160,1.000000,0.263158,0.246445,0.571429,0.250000,1.0,True,GSW,2022

In [69]:
print(df_rolling.dtypes)

mp           float64
fg           float64
fga          float64
fg%          float64
3p           float64
              ...
total_opp    float64
home_opp     float64
won             bool
team          object
season         int64
Length: 139, dtype: object

In [70]:
#Pandas method rolling 
# Grouping by season to take account team's changement (free agency, coach, trades)
def find_team_averages(team):
    #rolling = team.rolling(10).mean()
    print(team)
    return team#rolling

df_rolling  = df_rolling.groupby(["team","season"], group_keys=False).mean()

In [71]:
df_rolling

                   mp        fg       fga       fg%        3p       3pa  \
team season
ATL  2016    0.019886  0.436983  0.360127  0.444304  0.346787  0.375861
     2017    0.024691  0.434063  0.364561  0.435936  0.308216  0.337636
     2018    0.003165  0.433544  0.375652  0.427604  0.384548  0.407748
     2019    0.022436  0.511946  0.467949  0.443930  0.450044  0.496503
     2020    0.033333  0.495833  0.449510  0.441446  0.416092  0.488384
...               ...       ...       ...       ...       ...       ...
WAS  2018    0.020833  0.481061  0.378676  0.483219  0.339901  0.337482
     2019    0.032051  0.525932  0.439480  0.482237  0.392131  0.442502
     2020    0.011538  0.505944  0.453394  0.449935  0.417507  0.439860
     2021    0.016447  0.548445  0.453947  0.495371  0.342105  0.371411
     2022    0.018987  0.487629  0.381794  0.487388  0.363597  0.405639

                  3p%        ft       fta       ft%  ...  ast%_max_opp  \
team season                                          ...
ATL  2016    0.415272  0.340381  0.299964  0.743649  ...      0.348806
     2017    0.403067  0.411427  0.389771  0.684328  ...      0.358053
     2018    0.431898  0.349720  0.307615  0.754235  ...      0.360643
     2019    0.420336  0.386106  0.356736  0.706445  ...      0.344345
     2020    0.395507  0.403876  0.353439  0.749086  ...      0.277676
...               ...       ...       ...       ...  ...           ...
WAS  2018    0.443714  0.373477  0.331633  0.744763  ...      0.296841
     2019    0.405445  0.406977  0.366097  0.726745  ...      0.323086
     2020    0.436762  0.430411  0.375824  0.748927  ...      0.312773
     2021    0.415177  0.453182  0.404135  0.741724  ...      0.287422
     2022    0.407574  0.380041  0.333333  0.752448  ...      0.332046

             stl%_max_opp  blk%_max_opp  tov%_max_opp  usg%_max_opp  \
team season
ATL  2016        0.073477      0.076920      0.382790      0.167187
     2017        0.061222      0.089951      0.439540      0.174725
     2018        0.057861      0.097658      0.379229      0.134447
     2019        0.060167      0.096731      0.364471      0.150801
     2020        0.061783      0.100083      0.362736      0.160441
...                   ...           ...           ...           ...
WAS  2018        0.062024      0.077917      0.385744      0.157283
     2019        0.048808      0.080705      0.376512      0.164214
     2020        0.053400      0.077277      0.359603      0.152167
     2021        0.056737      0.082882      0.396378      0.171340
     2022        0.053848      0.091430      0.333373      0.169724

             ortg_max_opp  drtg_max_opp  total_opp  home_opp       won
team season
ATL  2016        0.386094      0.416396   0.347137  0.500000  0.545455
     2017        0.408402      0.432834   0.389126  0.493827  0.518519
     2018        0.416762      0.429476   0.432449  0.506329  0.291139
     2019        0.417730      0.470849   0.530572  0.487179  0.358974
     2020        0.405924      0.453373   0.531090  0.483333  0.283333
...                   ...           ...        ...       ...       ...
WAS  2018        0.415708      0.484694   0.402244  0.488095  0.535714
     2019        0.421011      0.490385   0.509615  0.500000  0.384615
     2020        0.419614      0.489377   0.518639  0.461538  0.353846
     2021        0.397543      0.495614   0.526189  0.500000  0.460526
     2022        0.441898      0.490808   0.462756  0.506329  0.430380

[210 rows x 137 columns]

In [72]:
rolling_cols = [f"{col}_10" for col in df_rolling.columns]
df_rolling.columns = rolling_cols

df = pd.concat([df, df_rolling], axis=1)
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,ast%_max_opp_10,stl%_max_opp_10,blk%_max_opp_10,tov%_max_opp_10,usg%_max_opp_10,ortg_max_opp_10,drtg_max_opp_10,total_opp_10,home_opp_10,won_10
0,0.0,0.363636,0.338235,0.368675,0.206897,0.212121,0.395487,0.418605,0.412698,0.654609,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.0,0.431818,0.500000,0.325301,0.310345,0.378788,0.368171,0.209302,0.253968,0.519253,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.0,0.409091,0.397059,0.375904,0.241379,0.227273,0.437055,0.348837,0.349206,0.645274,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.0,0.500000,0.529412,0.380723,0.310345,0.393939,0.356295,0.441860,0.333333,0.893816,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.0,0.409091,0.323529,0.438554,0.275862,0.348485,0.351544,0.255814,0.222222,0.766628,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"(WAS, 2018)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.296841,0.062024,0.077917,0.385744,0.157283,0.415708,0.484694,0.402244,0.488095,0.535714
"(WAS, 2019)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.323086,0.048808,0.080705,0.376512,0.164214,0.421011,0.490385,0.509615,0.500000,0.384615
"(WAS, 2020)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.312773,0.053400,0.077277,0.359603,0.152167,0.419614,0.489377,0.518639,0.461538,0.353846
"(WAS, 2021)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.287422,0.056737,0.082882,0.396378,0.171340,0.397543,0.495614,0.526189,0.500000,0.460526
"(WAS, 2022)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.332046,0.053848,0.091430,0.333373,0.169724,0.441898,0.490808,0.462756,0.506329,0.430380

In [74]:
#Improve accuracy by knowing the next "home" game for each team

def add_next_cols(df, col_name):
    grouped = df.groupby("team", group_keys=False)
    df[col_name + "_next"] = grouped[col_name].shift(-1)
    return df

# Add columns to the DataFrame
df = add_next_cols(df, "home")
df = add_next_cols(df, "team_opp")
df = add_next_cols(df, "date")

# Print the resulting DataFrame
print(df)

Empty DataFrame
Columns: [mp, fg, fga, fg%, 3p, 3pa, 3p%, ft, fta, ft%, orb, drb, trb, ast, stl, blk, tov, pf, pts, ts%, efg%, 3par, ftr, orb%, drb%, trb%, ast%, stl%, blk%, tov%, usg%, ortg, drtg, fg_max, fga_max, fg%_max, 3p_max, 3pa_max, 3p%_max, ft_max, fta_max, ft%_max, orb_max, drb_max, trb_max, ast_max, stl_max, blk_max, tov_max, pf_max, pts_max, +/-_max, ts%_max, efg%_max, 3par_max, ftr_max, orb%_max, drb%_max, trb%_max, ast%_max, stl%_max, blk%_max, tov%_max, usg%_max, ortg_max, drtg_max, team, total, home, mp_opp, fg_opp, fga_opp, fg%_opp, 3p_opp, 3pa_opp, 3p%_opp, ft_opp, fta_opp, ft%_opp, orb_opp, drb_opp, trb_opp, ast_opp, stl_opp, blk_opp, tov_opp, pf_opp, pts_opp, ts%_opp, efg%_opp, 3par_opp, ftr_opp, orb%_opp, drb%_opp, trb%_opp, ast%_opp, stl%_opp, blk%_opp, tov%_opp, usg%_opp, ...]
Index: []

[0 rows x 282 columns]

C:\Users\clmen\AppData\Local\Temp\ipykernel_4476\3088190492.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name + "_next"] = grouped[col_name].shift(-1)
C:\Users\clmen\AppData\Local\Temp\ipykernel_4476\3088190492.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name + "_next"] = grouped[col_name].shift(-1)
C:\Users\clmen\AppData\Local\Temp\ipykernel_4476\3088190492.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[col_name + "_next"] = grouped[col_name].shift(-1)

In [75]:
df

Empty DataFrame
Columns: [mp, fg, fga, fg%, 3p, 3pa, 3p%, ft, fta, ft%, orb, drb, trb, ast, stl, blk, tov, pf, pts, ts%, efg%, 3par, ftr, orb%, drb%, trb%, ast%, stl%, blk%, tov%, usg%, ortg, drtg, fg_max, fga_max, fg%_max, 3p_max, 3pa_max, 3p%_max, ft_max, fta_max, ft%_max, orb_max, drb_max, trb_max, ast_max, stl_max, blk_max, tov_max, pf_max, pts_max, +/-_max, ts%_max, efg%_max, 3par_max, ftr_max, orb%_max, drb%_max, trb%_max, ast%_max, stl%_max, blk%_max, tov%_max, usg%_max, ortg_max, drtg_max, team, total, home, mp_opp, fg_opp, fga_opp, fg%_opp, 3p_opp, 3pa_opp, 3p%_opp, ft_opp, fta_opp, ft%_opp, orb_opp, drb_opp, trb_opp, ast_opp, stl_opp, blk_opp, tov_opp, pf_opp, pts_opp, ts%_opp, efg%_opp, 3par_opp, ftr_opp, orb%_opp, drb%_opp, trb%_opp, ast%_opp, stl%_opp, blk%_opp, tov%_opp, usg%_opp, ...]
Index: []

[0 rows x 282 columns]